### ISSUE TITLE
21時ごろ胡町付近を検索するとエラーが発生

### ISSUE THREAD

**Issue by eiel** [parkmap-h/parkmap#122]
```
126.253.9.138 - - [11/Apr/2015:12:40:09 +0000] "POST /500 HTTP/1.1" 500 48 0.3117
Started POST "/.json" for 126.253.9.138 at 2015-04-11 12:40:09 +0000
Processing by HomeController#search as JSON
  Parameters: {"distance"=>"300", "longitude"=>"132.4655270576477", "latitude"=>"34.39329451672942"}
Can't verify CSRF token authenticity
  Park Load (2.0ms)  SELECT st_distance("parks"."geog", '0020000001000010e640608ee5990000004041325779878645'), * FROM "parks" WHERE st_distance("parks"."geog", '0020000001000010e640608ee5990000004041325779878645') < '300'
  ParkPhoto Load (0.6ms)  SELECT "park_photos".* FROM "park_photos" WHERE "park_photos"."park_id" IN (1, 15, 48, 49, 50, 52, 67, 70, 73, 81, 85, 89, 92, 97, 111, 114, 115, 112, 113, 75, 91, 71, 72, 90, 86, 87, 109, 108, 98, 94, 95, 136, 137, 140, 76, 139, 138, 120, 119, 118, 68, 152, 158, 154, 155, 195, 194, 193, 192, 191, 189, 188, 185, 184, 196, 211, 183, 156, 151, 74, 24, 107, 106, 88, 102, 93)
  PostPhoto Load (0.9ms)  SELECT "post_photos".* FROM "post_photos" WHERE "post_photos"."id" IN (26, 69, 68, 66, 65, 105, 100, 97, 86, 126, 122, 119, 113, 134, 137, 139, 135, 136, 92, 120, 99, 98, 121, 125, 124, 132, 131, 112, 117, 116, 164, 165, 168, 91, 167, 166, 146, 145, 142, 103, 184, 191, 186, 187, 221, 222, 223, 224, 225, 227, 228, 192, 193, 220, 248, 194, 188, 183, 95, 44, 130, 129, 123, 108, 118)
  Rendered home/search.json.jbuilder (141.5ms)
Completed 500 Internal Server Error in 143ms

ActionView::Template::Error (undefined method `last' for nil:NilClass):
    13:     json.photos park.photos.map {|photo| photo.photo.url}
    14:     json.mini_photos park.photos.map {|photo| photo.photo.mini.url}
    15:     json.thumb_photos park.photos.map {|photo| photo.photo.thumb.url}
    16:     json.hour_fee park.hour_fee
    17:   end
    18: end
  app/models/fee_calculator.rb:45:in `_times'
  app/models/fee_calculator.rb:87:in `_times'
  app/models/fee_calculator.rb:69:in `calc'
  app/models/fee_calculator.rb:79:in `hour_fee'
  app/models/park.rb:50:in `hour_fee'
  app/views/home/search.json.jbuilder:16:in `block (2 levels) in _app_views_home_search_json_jbuilder__729951910229779889_69920054931000'
  app/views/home/search.json.jbuilder:8:in `block in _app_views_home_search_json_jbuilder__729951910229779889_69920054931000'
  app/views/home/search.json.jbuilder:2:in `_app_views_home_search_json_jbuilder__729951910229779889_69920054931000'
```

**Comment by eiel** [comment]
```ruby
params = {"distance"=>"300", "longitude"=>"132.4655270576477", "latitude"=>"34.39329451672942"}.symbolize_keys
time = Time.zone.local(2015,04,12,21)
Park.search(params).map do |park| FeeCalculator.new(park.fee).houre_fee(time))
```

**Comment by eiel** [comment]
料金情報のデータに間違いがあったため発生していた。

9時から21時しかない状態になっていた。
同じ問題が起きないように登録するときにチェックすると良さそう。 #125
